In [5]:
import numpy as np

In [9]:
def generate_traffic_matrix(sending, receiving):
    # normalize vectors
    sending = sending / np.linalg.norm(sending)
    receiving = receiving / np.linalg.norm(receiving)

    # sending and receiving are vectors of length n, reshape them to be nx1 and 1xn
    sending = np.reshape(sending, (len(sending), 1))
    receiving = np.reshape(receiving, (1, len(receiving)))
    
    # multiply the two vectors to get an nxn matrix 
    matrix = sending @ receiving
    np.fill_diagonal(matrix, 0)
    
    return matrix / np.sum(matrix)

Different distributions for server popularity

In [12]:
def generate_unif(n):
    # generate a uniform vector of length n
    return np.ones(n) / n

In [13]:
def generate_random(n):
    # generate a random vector of length n
    popularities = np.random.rand(n)
    return popularities / np.linalg.norm(popularities)

In [14]:
def generate_gaussian(n, std=0.1):
    # generate a uniform vector of length n, with some Gaussian noise added. default std is 0.1
    popularities = np.random.rand(n) + np.random.normal(0, std, n)
    return popularities / np.linalg.norm(popularities)

In [15]:
# Generate popularities according to Pareto dist

def generate_zipf(n, repeat=1):
    """Returns nodes' popularities according to Zipf dist
    ARGS:
        n: number of nodes
        repeat: number of nodes with 1/i popularity
        
    OUTPUTS:
        popularities: list of popularity for each node, following an approximate Zipf distribution
    """
    
    popularities = np.array([1/np.ceil(i/repeat) for i in range(1,n+1)]) # repeated Zipf function
    return popularities / np.linalg.norm(popularities) # normalize


Testing

In [10]:
unif_10 = generate_unif(10)
generate_traffic_matrix(unif_10, unif_10)

array([[0.        , 0.01111111, 0.01111111, 0.01111111, 0.01111111,
        0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.        , 0.01111111, 0.01111111, 0.01111111,
        0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.        , 0.01111111, 0.01111111,
        0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.01111111, 0.        , 0.01111111,
        0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.        ,
        0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111,
        0.        , 0.01111111, 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.01111111, 0.01111111, 0.01111111,
        0.01111111, 0.        , 0.01111111, 0.01111111, 0.01111111],
       [0.01111111, 0.01111111, 0.0111111

In [16]:
rand_10 = generate_random(10)
generate_traffic_matrix(rand_10, rand_10)

array([[0.        , 0.00751518, 0.00494292, 0.00251315, 0.00321322,
        0.00952697, 0.00839917, 0.00410822, 0.00218782, 0.00992138],
       [0.00751518, 0.        , 0.0140973 , 0.00716757, 0.00916418,
        0.02717111, 0.02395461, 0.01171672, 0.0062397 , 0.02829597],
       [0.00494292, 0.0140973 , 0.        , 0.00471428, 0.0060275 ,
        0.0178711 , 0.01575553, 0.00770637, 0.004104  , 0.01861095],
       [0.00251315, 0.00716757, 0.00471428, 0.        , 0.0030646 ,
        0.0090863 , 0.00801067, 0.0039182 , 0.00208662, 0.00946247],
       [0.00321322, 0.00916418, 0.0060275 , 0.0030646 , 0.        ,
        0.0116174 , 0.01024214, 0.00500965, 0.00266787, 0.01209835],
       [0.00952697, 0.02717111, 0.0178711 , 0.0090863 , 0.0116174 ,
        0.        , 0.03036719, 0.01485326, 0.00791004, 0.03587072],
       [0.00839917, 0.02395461, 0.01575553, 0.00801067, 0.01024214,
        0.03036719, 0.        , 0.01309494, 0.00697366, 0.03162436],
       [0.00410822, 0.01171672, 0.0077063

In [17]:
gaus_10 = generate_gaussian(10)
generate_traffic_matrix(gaus_10, gaus_10)

array([[0.        , 0.02682179, 0.01735867, 0.02000415, 0.01414235,
        0.00960772, 0.0078175 , 0.01606421, 0.02092353, 0.00093035],
       [0.02682179, 0.        , 0.02215536, 0.02553186, 0.01805028,
        0.0122626 , 0.0099777 , 0.0205032 , 0.0267053 , 0.00118743],
       [0.01735867, 0.02215536, 0.        , 0.01652385, 0.01168188,
        0.00793618, 0.00645742, 0.01326937, 0.01728328, 0.00076849],
       [0.02000415, 0.02553186, 0.01652385, 0.        , 0.01346221,
        0.00914566, 0.00744154, 0.01529164, 0.01991727, 0.0008856 ],
       [0.01414235, 0.01805028, 0.01168188, 0.01346221, 0.        ,
        0.00646571, 0.00526095, 0.01081074, 0.01408093, 0.0006261 ],
       [0.00960772, 0.0122626 , 0.00793618, 0.00914566, 0.00646571,
        0.        , 0.00357407, 0.00734436, 0.00956599, 0.00042534],
       [0.0078175 , 0.0099777 , 0.00645742, 0.00744154, 0.00526095,
        0.00357407, 0.        , 0.00597588, 0.00778355, 0.00034609],
       [0.01606421, 0.0205032 , 0.0132693

In [18]:
zipf_10 = generate_zipf(10, repeat=1)
generate_traffic_matrix(zipf_10, zipf_10)

array([[0.        , 0.07113299, 0.04742199, 0.0355665 , 0.0284532 ,
        0.023711  , 0.02032371, 0.01778325, 0.01580733, 0.0142266 ],
       [0.07113299, 0.        , 0.023711  , 0.01778325, 0.0142266 ,
        0.0118555 , 0.01016186, 0.00889162, 0.00790367, 0.0071133 ],
       [0.04742199, 0.023711  , 0.        , 0.0118555 , 0.0094844 ,
        0.00790367, 0.00677457, 0.00592775, 0.00526911, 0.0047422 ],
       [0.0355665 , 0.01778325, 0.0118555 , 0.        , 0.0071133 ,
        0.00592775, 0.00508093, 0.00444581, 0.00395183, 0.00355665],
       [0.0284532 , 0.0142266 , 0.0094844 , 0.0071133 , 0.        ,
        0.0047422 , 0.00406474, 0.00355665, 0.00316147, 0.00284532],
       [0.023711  , 0.0118555 , 0.00790367, 0.00592775, 0.0047422 ,
        0.        , 0.00338729, 0.00296387, 0.00263456, 0.0023711 ],
       [0.02032371, 0.01016186, 0.00677457, 0.00508093, 0.00406474,
        0.00338729, 0.        , 0.00254046, 0.00225819, 0.00203237],
       [0.01778325, 0.00889162, 0.0059277

In [19]:
generate_traffic_matrix(unif_10, zipf_10)
# uniformly sending messages, but some are more popular receivers

array([[0.        , 0.01896762, 0.01264508, 0.00948381, 0.00758705,
        0.00632254, 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.        , 0.01264508, 0.00948381, 0.00758705,
        0.00632254, 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.        , 0.00948381, 0.00758705,
        0.00632254, 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.01264508, 0.        , 0.00758705,
        0.00632254, 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.01264508, 0.00948381, 0.        ,
        0.00632254, 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.01264508, 0.00948381, 0.00758705,
        0.        , 0.00541932, 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.01264508, 0.00948381, 0.00758705,
        0.00632254, 0.        , 0.0047419 , 0.00421503, 0.00379352],
       [0.03793524, 0.01896762, 0.0126450