In [1]:
import numpy as np

In [10]:
def generate_traffic_matrix(sending, receiving):
    # normalize vectors
    sending = sending / np.linalg.norm(sending)
    receiving = receiving / np.linalg.norm(receiving)

    # sending and receiving are vectors of length n, reshape them to be nx1 and 1xn
    sending = np.reshape(sending, (len(sending), 1))
    receiving = np.reshape(receiving, (1, len(receiving)))

    # multiply the two vectors to get an nxn matrix
    return sending @ receiving


Different distributions for server popularity

In [14]:
def generate_unif(n):
    # generate a uniform vector of length n
    return np.ones(n) / n

In [15]:
def generate_random(n):
    # generate a random vector of length n
    popularities = np.random.rand(n)
    return popularities / np.linalg.norm(popularities)

In [16]:
def generate_gaussian(n, std=0.1):
    # generate a uniform vector of length n, with some Gaussian noise added. default std is 0.1
    popularities = np.random.rand(n) + np.random.normal(0, std, n)
    return popularities / np.linalg.norm(popularities)

In [11]:
# Generate popularities according to Pareto dist

def generate_zipf(n, repeat=1):
    """Returns nodes' popularities according to Zipf dist
    ARGS:
        n: number of nodes
        repeat: number of nodes with 1/i popularity
        
    OUTPUTS:
        popularities: list of popularity for each node, following an approximate Zipf distribution
    """
    
    popularities = np.array([1/np.ceil(i/repeat) for i in range(1,n+1)]) # repeated Zipf function
    return popularities / np.linalg.norm(popularities) # normalize


Testing

In [17]:
unif_10 = generate_unif(10)
generate_traffic_matrix(unif_10, unif_10)

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]])

In [18]:
rand_10 = generate_random(10)
generate_traffic_matrix(rand_10, rand_10)

array([[2.41472073e-01, 5.47450103e-03, 1.49718340e-01, 2.06355839e-01,
        1.62865529e-02, 1.85222751e-01, 9.11899007e-02, 5.59745980e-02,
        2.12573646e-01, 1.64091436e-01],
       [5.47450103e-03, 1.24114400e-04, 3.39431885e-03, 4.67836813e-03,
        3.69238354e-04, 4.19925224e-03, 2.06739934e-03, 1.26902043e-03,
        4.81933429e-03, 3.72017651e-03],
       [1.49718340e-01, 3.39431885e-03, 9.28288775e-02, 1.27945453e-01,
        1.00980442e-02, 1.14842444e-01, 5.65398741e-02, 3.47055617e-02,
        1.31800639e-01, 1.01740533e-01],
       [2.06355839e-01, 4.67836813e-03, 1.27945453e-01, 1.76346406e-01,
        1.39180703e-02, 1.58286611e-01, 7.79285497e-02, 4.78344554e-02,
        1.81659984e-01, 1.40228331e-01],
       [1.62865529e-02, 3.69238354e-04, 1.00980442e-02, 1.39180703e-02,
        1.09847819e-03, 1.24927082e-02, 6.15047995e-03, 3.77531547e-03,
        1.43374424e-02, 1.10674656e-02],
       [1.85222751e-01, 4.19925224e-03, 1.14842444e-01, 1.58286611e-01,
   

In [19]:
gaus_10 = generate_gaussian(10)
generate_traffic_matrix(gaus_10, gaus_10)

array([[0.24316581, 0.14268194, 0.18444869, 0.05850045, 0.15249411,
        0.0154647 , 0.12381727, 0.21386821, 0.09711611, 0.17955211],
       [0.14268194, 0.08372121, 0.10822861, 0.0343262 , 0.08947868,
        0.00907419, 0.07265202, 0.12549104, 0.05698463, 0.10535545],
       [0.18444869, 0.10822861, 0.13990997, 0.04437438, 0.11567144,
        0.01173044, 0.09391918, 0.16222557, 0.07366554, 0.13619576],
       [0.05850045, 0.0343262 , 0.04437438, 0.01407394, 0.03668679,
        0.00372047, 0.02978776, 0.05145208, 0.02336404, 0.04319636],
       [0.15249411, 0.08947868, 0.11567144, 0.03668679, 0.09563209,
        0.00969822, 0.07764827, 0.13412101, 0.06090344, 0.1126007 ],
       [0.0154647 , 0.00907419, 0.01173044, 0.00372047, 0.00969822,
        0.00098351, 0.00787445, 0.01360145, 0.00617633, 0.01141904],
       [0.12381727, 0.07265202, 0.09391918, 0.02978776, 0.07764827,
        0.00787445, 0.06304635, 0.10889927, 0.04945042, 0.0914259 ],
       [0.21386821, 0.12549104, 0.1622255

In [13]:
zipf_10 = generate_zipf(10, repeat=1)
generate_traffic_matrix(zipf_10, zipf_10)

array([[0.64525798, 0.32262899, 0.21508599, 0.1613145 , 0.1290516 ,
        0.107543  , 0.09217971, 0.08065725, 0.07169533, 0.0645258 ],
       [0.32262899, 0.1613145 , 0.107543  , 0.08065725, 0.0645258 ,
        0.0537715 , 0.04608986, 0.04032862, 0.03584767, 0.0322629 ],
       [0.21508599, 0.107543  , 0.07169533, 0.0537715 , 0.0430172 ,
        0.03584767, 0.03072657, 0.02688575, 0.02389844, 0.0215086 ],
       [0.1613145 , 0.08065725, 0.0537715 , 0.04032862, 0.0322629 ,
        0.02688575, 0.02304493, 0.02016431, 0.01792383, 0.01613145],
       [0.1290516 , 0.0645258 , 0.0430172 , 0.0322629 , 0.02581032,
        0.0215086 , 0.01843594, 0.01613145, 0.01433907, 0.01290516],
       [0.107543  , 0.0537715 , 0.03584767, 0.02688575, 0.0215086 ,
        0.01792383, 0.01536329, 0.01344287, 0.01194922, 0.0107543 ],
       [0.09217971, 0.04608986, 0.03072657, 0.02304493, 0.01843594,
        0.01536329, 0.01316853, 0.01152246, 0.01024219, 0.00921797],
       [0.08065725, 0.04032862, 0.0268857

In [20]:
generate_traffic_matrix(unif_10, zipf_10)
# uniformly sending messages, but some are more popular receivers

array([[0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731 , 0.06350482, 0.05080386,
        0.04233655, 0.03628847, 0.03175241, 0.02822437, 0.02540193],
       [0.25401929, 0.12700964, 0.0846731